import React from 'react';
import Head from "next/head";
import {Alert, Avatar, Card, Col, Layout, Menu, MenuProps, Row, Tag, theme, Timeline, Typography} from "antd";
import {GithubOutlined} from "@ant-design/icons";
import Link from "next/link";

const { Header, Content, Footer } = Layout;
const { Text, Paragraph } = Typography;

const gnbItems: MenuProps['items'] = [
  {
    'key': '1',
    'label': (
      <Link href="/">Portfolio</Link>
    )
  },
  {
    'key': '2',
    'label': (
      <Link href="/About">About me</Link>
    )
  }
];

const { Meta } = Card;

const About = () => {
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <>
      <Head>
        <title>Jintae Kim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout className="layout" style={{ background: '#f5f5f5' }}>
          <Header style={{ position: 'sticky', top: 0, zIndex: 1, width: '100%', padding: 0, background: colorBgContainer }}>
            <Menu
              theme="light"
              mode="horizontal"
              defaultSelectedKeys={['2']}
              items={gnbItems}
            />
          </Header>
          <Content style={{ padding: '24px' }}>
            <Row>
              <Col span={24}>
                <Card bordered={false}>
                  <Meta
                    title="김 진태"
                    description={
                      <>
                        <Paragraph type="secondary">
                          Jintae Kim<br />
                          <a href="mailto:vuenos@gmail.com">vuenos@gmail.com</a>, <a
                          href="mailto:jintae.email@gmail.com">jintae.email@gmail.com</a><br />
                          <GithubOutlined /> <a href="https://github.com/vuenos" target="_blank" rel="noreferrer">https://github.com/vuenos</a>
                        </Paragraph>

                        <Paragraph style={{ marginTop: '40px' }}>
                          1976년 경기도 부천 태생, 2남 1녀 중 차남. 건축학 전공.<br />
                          현재 경기도 고양시 10년째 거주.<br />
                        </Paragraph>
                      </>
                    }
                  />
                </Card>
              </Col>
            </Row>

          </Content>
          <Footer style={{ textAlign: 'center' }}>
            <Paragraph type="secondary">©2024 Jintae kim</Paragraph>
            <Paragraph type="secondary">
              이 페이지는 <a href="https://ko.reactjs.org/" target="_blank" rel="noreferrer">React 18</a>, <a href="https://www.typescriptlang.org/" target="_blank" rel="noreferrer">TypeScript</a>, <a href="https://nextjs.org/blog/next-13" target="_blank" rel="noreferrer">Next.js 13</a> 과 <a href="https://ant.design" target="_blank" rel="noreferrer">Antd</a> 로 제작되었습니다.
            </Paragraph>
          </Footer>
        </Layout>
      </main>
    </>
  )
}
export default About;
