import Head from 'next/head';
import Image from 'next/image';
import { MenuProps } from "antd";
import { Layout, theme, Typography, Menu, Row, Col, Avatar, Space, List, Card, Timeline, Tag } from "antd";
import Link from 'next/link';
import { UserOutlined, IdcardOutlined, ClockCircleOutlined } from "@ant-design/icons"

const { Header, Content, Footer } = Layout;
const { Text, Paragraph } = Typography;

const gnbItems: MenuProps['items'] = [
  {
    'key': '1',
    'label': (
      <Link href="#">Portfolio</Link>
    )
  },
  {
    'key': '2',
    'label': (
      <Link href="#">About me</Link>
    )
  }
];

const { Meta } = Card;

const myData = [
  {
    title: '김 진태',
    description: 'Jintae kim'
  },
  {
    title: 'Contact',
    description: (
      <Paragraph type="secondary">
        vuenos@gmail.com<br />
        +82 10-4860-6521
      </Paragraph>
    )
  }
];

const year2023 = [
  {
    dot: <ClockCircleOutlined style={{ fontSize: '16px' }} />,
    label: (<Tag color="#108ee9">셀러허브 2023 .02</Tag>),
    children: '현재 재직 중',
    color: 'green',
  },
  {
    label: (<Tag color="#108ee9">셀러허브 2022 .04</Tag>),
    children:
      <>
        <Paragraph>
          셀러허브 공식 홈페이지 개편<br />
          셀러허브 3.0 API 를 활용하여 REST 아키텍쳐 구현(Restful)
        </Paragraph>
        <Paragraph>
          <Tag color="red">React</Tag>
          <Tag color="red">Typescript</Tag>
          <Tag color="red">Scss</Tag>
          <Tag color="red">npm, webpack</Tag>
        </Paragraph>
      </>
    ,
  },
  {
    label: (<Tag color="#108ee9">셀러허브 2021 .09</Tag>),
    children: (
      <>
        <Paragraph>
          dropk(beta) - 한국 제품을 미국으로 판매하는 드랍쉬핑 개념의 플랫폼<br />
          blade template 으로 front 구현
        </Paragraph>
        <Paragraph>
          <Tag color="red">javaScript</Tag>
          <Tag color="red">blade template</Tag>
        </Paragraph>
      </>
    ),
  },
  {
    label: (<Tag color="#108ee9">셀러허브 2021 .06</Tag>),
    children: (
      <>
        <Paragraph>
          shopify 기반 &quot;올타리 몰&quot; 온라인 쇼핑몰 구축 참여(Front, UI)<br />
          <a href="https://wooltariusa.com" target="_blank" rel="noreferrer">https://wooltariusa.com</a><br />
        </Paragraph>
        <Paragraph>
          <Tag color="red">liquid</Tag>
          <Tag color="red">shopify CLI</Tag>
          <Tag color="red">javaScript</Tag>
        </Paragraph>
      </>
    ),
  },
  {
    dot: <ClockCircleOutlined style={{ fontSize: '16px' }} />,
    label: (<Tag color="#87d068">2021 .03</Tag>),
    children: (
      <>
        <Paragraph>
          고용보험 민원서비스 고도화(web, mobile)<br />
          실업급여 인터넷 신청 단계별 UI 를 javaScript 로 구현<br />
          <a href="https://www.ei.go.kr" target="_blank" rel="noreferrer">https://www.ei.go.kr</a>
        </Paragraph>
        <Paragraph>
          <Tag color="red">javaScript, jQuery</Tag>
          <Tag color="red">HTML5</Tag>
        </Paragraph>
      </>
    ),
  },
]

export default function Home() {
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <>
      <Head>
        <title>Jintae Kim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout className="layout" style={{ background: '#f5f5f5' }}>
          <Header style={{ position: 'sticky', top: 0, zIndex: 1, width: '100%', padding: 0, background: colorBgContainer }}>
            <Menu
              theme="light"
              mode="horizontal"
              defaultSelectedKeys={['1']}
              items={gnbItems}
            />
          </Header>
          <Content style={{ maxWidth: '1680px', margin: '0', padding: '24px' }}>
            <Row
              gutter={[16, 16]}
              style={{ padding: 0, minHeight: 380, background: '#f5f5f5' }}
            >
              <Col md={6} sm={24}>
                <Card bordered={false}>
                  <Meta
                    avatar={<Avatar src="https://joeschmoe.io/api/v1/random" size={80} />}
                    title="김 진태"
                    description={
                      <Paragraph type="secondary">
                        Jintae Kim<br />
                        vuenos@gmail.com<br />
                        +82 10-4860-6521
                      </Paragraph>
                    }
                  />
                </Card>
              </Col>

              <Col md={18} sm={24}>
                <Card title="2021 ~ 2023" bordered={false}>
                  <Timeline
                    mode="alternate"
                    items={year2023}
                  />
                </Card>
              </Col>
            </Row>
          </Content>
          <Footer style={{ textAlign: 'center' }}>
            <Paragraph type="secondary">©2023 Jintae kim</Paragraph>
            <Paragraph type="secondary">
              이 페이지는 React 18, Typescript, <a href="https://nextjs.org/blog/next-13" target="_blank" rel="noreferrer">Next.js 13</a> 과 <a href="https://ant.design" target="_blank" rel="noreferrer">Antd</a> 로 제작되었습니다.
            </Paragraph>
          </Footer>
        </Layout>
      </main>
    </>
  )
}
